# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #    
#                                                                                               #
#                                            CGACG                                              #
#                                     Created by eliotesta98                                    #
#                                                                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #   

Configuration:

  # Set whether various plugins should be hooked into (I will also check if is enabled).
  Hooks:
    RevEnchants:
      Enabled: false
      RegionFlags:
        - "RevEnchants-Mine:ALLOW"
        - "RevEnchants-Explosive:ALLOW"
        - "RevEnchants-JackHammer:ALLOW"
        - "RevEnchants-ThorHammer:ALLOW"
        - "RevEnchants-Laser:ALLOW"
        - "RevEnchants-MeteorShower:ALLOW"
        - "RevEnchants-BigBang:ALLOW"
      # Set whether the plugin should drop the items like a normal RevEnchants mine,
      # if false, the plugin will drop the items like a normal CubeGenerator.
      DropsLikeRevEnchantsMine: false
    PlotSquared7: false
    ItemsAdder: false
    Lands:
      Enabled: false
      # Excluded Lands (names)
      ExcludedLands:
        - "Widerness"
    AxBoosters: false
    WildTools: false
    AdvancedEnchantments: false
    McMMO:
      Enabled: false
      GiveExperience: true

# You can use a different coloring by using a hexadecimal for all messages Ex.&{#FFFF00}(yellow).
# Example for the message: {prefix}&{#FFFF00}You cannot place the CubeGenerator &a&lin this claim!
Messages:
  Prefix: '&eCubeGenerator &r'
  Lands:
    ChunkClaimed: '{prefix}&cYou cannot place the CubeGenerator in this claim!'

Debug:
  # Enabled time execution
  Enabled: false
  # Disabled time execution
  Disabled: false
  # Compatibility debug
  Compatibility: false
  # Add Material of CubeGenerator debug
  AddMaterialInventoryEvent: false