name: CGACG
version: maven-version-number
main: io.eliotesta98.CGACG.Core.Main
api-version: 1.13
authors: [ eliotesta98 ]
softdepend: [ WorldGuard,RevEnchants ]
depend: [ CubeGenerator ]
commands: { }
permissions: { }